config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: 'user_registrations' }
  # devise_for :users
  resources :users

  resources :products do
    resources :comments
  end

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  get 'simple_pages/landing_page'

  post 'simple_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'

  root 'simple_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# I forgot to check in to authentication branch so this is
# to practice checking in on branches other than master

app/views/shared/_navigation_bar.html.erb
<!-- NAVIGATION BAR -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- BRAND -->
      <%= link_to "Chamisama", root_path, class: "navbar-brand" %>

    </div>

    <!-- RIGHT SIDE OF NAVIGATION BAR -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "About", simple_pages_about_path %></li>

        <li><%= link_to "Contact", simple_pages_contact_path %></li>

        <li>
          <%= form_with(url: products_path, method: 'get', local: true, class: "navbar-form") do |form| %>
          <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control", placeholder: "product" %>
          <%= form.submit 'Search', class: "btn btn-primary" %>
          <% end %>
        </li>

        <% if user_signed_in? %>
        <li><%= link_to "Orders", orders_path %></li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Products", products_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Green Teas", products_path({ :tea_color => "green"}) %></li>
            <li><%= link_to "Black Teas", products_path({ :tea_color => "black"}) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Japanese Teas", products_path({ :country => "Japan"}) %></li>
            <li><%= link_to "Chinese Teas", products_path({ :country => "China"}) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Tea Accessories", products_path({ :tea_color => ""}) %></li>
          </ul>
        </li>

        <% if user_signed_in? %>
        <li class="dropdown">
          <% if current_user.first_name == "" || !current_user.first_name %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <% else %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name.capitalize %> <span class="caret"></span></a>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Change Personal Info", edit_user_path(current_user) %></li>
            <li><%= link_to "Change Account Info", edit_user_registration_path %></li>
          </ul>
        </li>
        <% else %>
        <%= link_to('Login', new_user_session_path, class: 'btn btn-primary navbar-btn', id: 'sign-in-or-out-button') %>
        <% end %>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- END NAVIGATION BAR -->

app/views/shared/_stripe_checkout_button.html.erb
<!-- <script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="/square-image.png"
  data-name="Demo Site"
  data-description="2 widgets ($20.00)"
  data-amount="2000">
</script> -->

<script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-amount="<%= @product.price_in_pennies %>"
    data-name="<%= @product.name %>"
    data-description=" <%= @product.description %>"
    data-image="https://s3-us-west-2.amazonaws.com/billhorst.com/chamisamaLogo.png"
    data-locale="auto">
  </script>